---
title: "Uova 2022"
author: "Giulia Bertoldo"
date: '2022-06-18'
output: html_document
---
```{r include=FALSE}
# Load packages
library(readxl)
library(tidyverse)
library(grid)

# Load data
df <- read_xlsx("eggs.xlsx")

# Explore data
glimpse(df)

# Calculate percentege eggs old and chickens
# Convert date type
df <- df %>%
  mutate(perc_egg_old = round((egg_old/chicken_old)*100, 2),
         perc_egg_new = round((egg_new/chicken_new)*100, 2))

```

# Line graphs

```{r echo=FALSE}
# Line graph only old
plot_old <- ggplot(data=df, aes(x=date, y=perc_egg_old)) +
  geom_line()+
  geom_point()+
  theme_bw()+
  labs(title = "Uova: Galline Vecchie",
       subtitle = "Percentuale di galline che hanno prodotto uova per giorno",
       y = "Percentuale galline",
       x = "Data")
plot_old

# Line graph only new
plot_new <- ggplot(data=df, aes(x=date, y=perc_egg_new)) +
  geom_line()+
  geom_point()+
  theme_bw()+
  labs(title = "Uova: Galline Nuove",
       subtitle = "Percentuale di galline che hanno prodotto uova per giorno",
       y = "Percentuale galline",
       x = "Data")
plot_new

# Place two graphs close 
grid.newpage()
pushViewport(viewport(layout=grid.layout(1,2)))
vplayout <- function(x, y) { viewport(layout.pos.row = x, layout.pos.col = y )
}
print(plot_old, vp = vplayout(1, 1))
print(plot_new, vp = vplayout(1,2)) 
```

# Scatterplot
```{r echo=FALSE}
# Line graph only old
plot_old <- ggplot(data=df, aes(x=date, y=perc_egg_old)) +
  geom_point()+
  theme_bw()+
  labs(title = "Uova: Galline Vecchie",
       subtitle = "Percentuale di galline che hanno prodotto uova per giorno",
       y = "Percentuale galline",
       x = "Data")
plot_old

# Line graph only new
plot_new <- ggplot(data=df, aes(x=date, y=perc_egg_new)) +
  geom_point()+
  theme_bw()+
  labs(title = "Uova: Galline Nuove",
       subtitle = "Percentuale di galline che hanno prodotto uova per giorno",
       y = "Percentuale galline",
       x = "Data")
plot_new

# Place two graphs close 
grid.newpage()
pushViewport(viewport(layout=grid.layout(1,2)))
vplayout <- function(x, y) { viewport(layout.pos.row = x, layout.pos.col = y )
}
print(plot_old, vp = vplayout(1, 1))
print(plot_new, vp = vplayout(1,2)) 
```

